white = "\033[1;37m"
normal = "\033[0;00m"
red = "\033[1;31m"
blue = "\033[1;34m"
green = "\033[1;32m"
lightblue = "\033[0;34m"
import os
print ("\033[1;35m                         ._________________.")
print ("                         | _______________ |")
print ("                         | I             I |")
print ("                         | I             I |")
print ("                         | I m o m u i l I |")
print ("                         | I             I |")
print ("                         | I_____________I |")
print ("                         !_________________!")
print ("                            ._[_______]_.")
print ("                        .___|___________|___.")
print ("                        |::: ____           |")
print ("                        |    ~~~~ [CD-ROM]  |")
print ("                        !___________________!")
pass
pass
pass
val=raw_input('\033[1;36m Enter Name Frindes :')
i=raw_input('\033[1;32m Enter The Name :')
l=raw_input('\033[1;33mEnter Number Phone :')
o=raw_input('\033[1;34m Enter Date of birth :')
g=raw_input('\033[1;35m Enter Name Father :')
a=('2018')
b=('2017')
k=('2016')
q=('12345')
v=('1212')
x=('1122')
z=('1010')
ii=('1234567890')
pp=('12345678910')
oo=('1234512345')
pass
pass
pass
pass
pass
pass
pass
pass
f=open('password.txt','w')
f.write("\n"+i+l)
f.write("\n"+l+i)
f.write("\n"+i+o)
f.write("\n"+o+i)
f.write("\n"+o+l)
f.write("\n"+i+g)
f.write("\n"+g+i)
f.write("\n"+i+a)
f.write("\n"+i+v)
f.write("\n"+i+ii)
f.write("\n"+i+oo)
f.write("\n"+i+z)
f.write("\n"+i+k)
f.write("\n"+l+pp)
f.write("\n"+g+k)
f.write("\n"+o+z)
f.write('qwerqwer \n')
f.write('zxcvzxcv')
f.write("\n"+i+pp)
f.write("\n"+o+k)
f.write("\n"+o+pp)
f.write("\n"+o+oo)
f.write("\n"+pp)
f.write("\n"+i+ii)
f.write("\n"+pp+oo)
f.write('\n mastermaster')
f.write('\n password')
f.write('\n monkymonky')
f.write('\n xnxxxnxx')
f.write('\n tiggertigger')
f.write('\n alialiali')
f.write('\n ahmedahmed')
f.write('\n hackerhacker')
f.write('\n hackhack')
f.write('\n 987654321')
f.write('\n 0987654321')
f.write('\n 19921922')
f.write('\n 20002000')
f.write('\n 20182018')
f.write('\n qwerty123')
f.write('\n 19911991')
f.write('\n 0102030405')
f.write('\n 102030405060708090')
f.write('\n 12121212')
f.write('\n qwerty1')
f.write("\n"+i+'00000')
f.write("\n"+oo+pp)
f.write("\n"+l+g)
f.write("\n"+val+i)
f.write("\n"+val+l)
f.write("\n"+val+pp)
f.write("\n"+val+g)
f.write("\n"+val+o)
f.write("\n"+val+k)
f.write("\n"+val+a)
f.write("\n"+val+z)
f.write("\n"+val+x)
f.write("\n"+val+v)
f.write("\n"+v+val)
f.write("\n"+x+val)
f.write("\n"+o+val)
f.write("\n"+a+val)
f.write("\n"+o+val)
f.write('\n imhacker')
f.write('\n fuckfuck')
f.write("\n"+val+q)
f.write("\n"+val+pp)
f.write("\n"+val+oo)
f.write("\n"+val+ii)
f.write("\n"+ii+val)
f.write("\n"+oo+val)
f.write("\n"+pp+val)
f.write('\n okokokok')
f.write("\n"+i+i)
f.write("\n"+l+l)
f.write("\n"+g+g)
f.write("\n"+o+o)
f.write("\n"+val+val)
f.write("\n flowrflowr")
f.write("\n minecraft")
f.write("\n 789456123")
f.write("\n"+i+'555')
f.write("\n"+i+'789')
f.write("\n 10"+i+'10')
f.write("\n qwert"+i) 
f.write("\n 1122334455"+i)
f.close()
print ("         \033[1;36m  Please Loading ./")
os.system('sleep 1')
print ("           Please Loading ../")
os.system('sleep 1')
print ("           Please Loading .../")
os.system('sleep 1')
print ("           Please Loading ..../")
os.system('sleep 1')
print ("           Please Loading ...../")
os.system('sleep 1')
print ("           Please Loading ....../")
os.system('sleep 1')
print ("           Please Loading ......./")
os.system('sleep 1')
print ("           Please Loading ......../")
os.system('sleep 1')
print ("           Please Loading ........./")
os.system('sleep 1')
print ("           Please Loading ........../")
os.system('sleep 1')
print ("           Please Loading .........../")
os.system('sleep 1')
print ("           Please Loading ............/")
os.system('sleep 1')
print ("           Please Loading ............./")
os.system('sleep 1')
print ("           Please Loading .............../")
os.system('sleep 1')
print ("           Please Loading ................./")
os.system('sleep 1')
print ("           Please Loading .................../")
os.system('sleep 1')
print ("           Please Loading ...................../")
os.system('sleep 1')
print ("           Please Loading ......................./")
os.system('sleep 5')
("         \033[1;36m  Please Loading ./")
os.system('sleep 1')
print ("           Please Loading ../")
os.system('sleep 1')
print ("           Please Loading .../")
os.system('sleep 1')
print ("           Please Loading ..../")
os.system('sleep 1')
print ("           Please Loading ...../")
os.system('sleep 1')
print ("           Please Loading ....../")
os.system('sleep 1')
print ("           Please Loading ......./")
os.system('sleep 1')
print ("           Please Loading ......../")
os.system('sleep 1')
print ("           Please Loading ........./")
os.system('sleep 1')
print ("           Please Loading ........../")
os.system('sleep 1')
print ("           Please Loading .........../")
os.system('sleep 1')
print ("           Please Loading ............/")
os.system('sleep 1')
print ("           Please Loading ............./")
os.system('sleep 1')
print ("           Please Loading .............../")
os.system('sleep 1')
print ("           Please Loading ................./")
os.system('sleep 1')
print ("           Please Loading .................../")
os.system('sleep 1')
print ("           Please Loading ...................../")
os.system('sleep 1')
print ("           Please Loading ......................./")
os.system('sleep 5')
print ("\n")
print ("\n")
print ("  	 	 ===============> NameList :> password.txt")
